### DISCUSSION TITLE
livekit connection error: could not establish pc connection

### DISCUSSION THREAD

**Discussion by Tylermeek** [mynaparrot/plugNmeet-server#399] [Q&A]
hello,I have been tried to run this project for couple days.But I am stuck by this livekit Error.
![image](https://github.com/mynaparrot/plugNmeet-server/assets/102410562/62ba384c-6001-4df0-90f4-11a3e3a157ea)
![image](https://github.com/mynaparrot/plugNmeet-server/assets/102410562/474c8f63-55af-4b15-81eb-0b5bc1fd5f6a)

It happened after I chose the way to enter the room. I tried to debug, in order to find out where the problem is. 
I found out that the connect method threw out this error.
![image](https://github.com/mynaparrot/plugNmeet-server/assets/102410562/2a2c4b92-a674-48c8-bc25-0d8a7f869f29)

This url and token should be correct.
So I went to check the Livekit server.  I tried for couple times, and found out that the connection closed after the perr connection tried to connect.
Here is part of the logs.
```
2024-01-06T11:15:23.930Z        DEBUG   livekit.transport       rtc/transport.go:643    peer connection state change    {"room": "room01", "roomID": "RM_6CdshrkrpaQC", "participant": "1704539345689", "pID": "PA_Xa6XWksuHksX", "remote": false, "transport": "SUBSCRIBER", "state": "connecting"}  
2024-01-06T11:15:38.860Z        INFO    livekit service/rtcservice.go:269       finishing WS connection {"room": "room01", "roomID": "RM_6CdshrkrpaQC", "participant": "1704539345689", "pID": "PA_Xa6XWksuHksX", "remote": false, "connID": "CO_SAWWK9u4Xa39", "closedByClient": true}  
2024-01-06T11:15:38.860Z        DEBUG   livekit service/rtcservice.go:335       nothing to read from response source    {"room": "room01", "roomID": "RM_6CdshrkrpaQC", "participant": "1704539345689", "pID": "PA_Xa6XWksuHksX", "remote": false, "connID": "CO_SAWWK9u4Xa39"}  
2024-01-06T11:15:38.861Z        DEBUG   livekit service/signal.go:168   signal stream closed    {"room": "room01", "participant": "1704539345689", "connID": "CO_SAWWK9u4Xa39", "error": null}
```
I don't know why the connection closed.About the firewall,my firewall didn't block the ports that livekit server need,but I still got that error.
Here is my livekit.yaml and config.yaml
``` yaml
# livekit.yaml
rtc:
  tcp_port: 7881
  udp_port: 7882
  stun_servers:
    - stun.l.google.com:19302
redis:
  address: redis:6379
  username: ""
  password: ""
  db: 0
#  use_tls: false
#  To use sentinel remove the host key above and add the following
#  sentinel_master_name: plugnmeet
#  sentinel_addresses:
#    - redis-sentinel-host-1:26379
#    - redis-sentinel-host-2:26379
#    - redis-sentinel-host-3:26379
#  If you use a different set of credentials for sentinel add
#  sentinel_username: user
#  sentinel_password: pass
room:
  enable_remote_unmute: true
  enabled_codecs:
    - mime: audio/opus
    - mime: audio/red
    - mime: video/vp8
    - mime: video/vp9
    - mime: video/av1
    - mime: video/h264
keys:
  APIiYAA5w37Cfo2: 6aNur7qqupeZhFYNOJVUyeXxXhVw8f4lm13pEDUx8SgB
signal_relay:
  enabled: true
psrpc:
  enabled: true
webhook:
  api_key: APIiYAA5w37Cfo2
  urls:
    # - "http://plugnmeet-api:8080/webhook"
    - "http://host.docker.internal:8080/webhook"
ingress:
  rtmp_base_url: rtmp://host.docker.internal:live
  whip_base_url: http://host.docker.internal:/whip
```

``` yaml
#config.yaml
client:
  port: 8080
  debug: true
  path: "/app/client/dist"
  ## this will require during authentication. Use random secret.
  # openssl rand -hex 32
  # OR
  # cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 36 | head -n 1
  api_key: "plugnmeet"
  secret: "zumyyYWqv7KR2kUqvYdq4z4sXg7XTBD2ljT6"
  webhook_conf:
    # enable webhook. This will post response for different events
    enable: false
    # set url bellow. This will be use as global.
    # this is optional
    url: ""
    # During create room you can set custom hook URL too.
    # if you set enable_for_per_meeting: true
    # then extra post response will send in that address too
    enable_for_per_meeting: false
  prometheus:
    enable: false
    metrics_path: "/metrics"
  proxy_header: "" ## you can set X-Forwarded-For
  copyright_conf:
    display: true
    text: 'Powered by <a href="https://www.plugnmeet.org" target="_blank">plugNmeet</a>'
room_default_settings:
  max_duration: 0 # Duration in minutes. 0 = no limit
  max_participants: 0 # 0 = no limit
log_settings:
  log_file: "./log/plugNmeet.log"
  # maxsize of log file in MB
  maxsize: 20
  maxbackups: 4
  # max age of log before rotate in days
  maxage: 2
livekit_info:
  host: "http://host.docker.internal:7880"
  api_key: "APIiYAA5w37Cfo2"
  secret: "6aNur7qqupeZhFYNOJVUyeXxXhVw8f4lm13pEDUx8SgB"
  # value in minutes. Default 10 minutes. Client will renew token automatically
  token_validity: 10m
redis_info:
  host: redis:6379
  username: ""
  password: ""
  db: 0
#  use_tls: false
#  To use sentinel remove the host key above and add the following
#  sentinel_master_name: plugnmeet
#  sentinel_addresses:
#    - redis-sentinel-host-1:26379
#    - redis-sentinel-host-2:26379
#    - redis-sentinel-host-3:26379
#  If you use a different set of credentials for sentinel add
#  sentinel_username: user
#  sentinel_password: pass
mysql_info:
  host: db
  port: 3306
  username: "root"
  password: "12345"
  db: "plugnmeet"
  prefix: "pnm_"
upload_file_settings:
  path: "./upload"
  # file size in MB. Default 10MB
  max_size: 10
  # By default, files will be deleted as soon as the session will be finish.
  # You can set it true to disable deleting files.
  keep_forever: false
  allowed_types:
    - "jpg"
    - "jpeg"
    - "png"
    - "svg"
    - "pdf"
    - "docx"
    - "zip"
recorder_info:
  # this value should be same as recorder's copy_to_dir path
  recording_files_path: "/app/recording_files"
  token_validity: 30m
shared_notepad:
  enabled: true
  # multiple hosts can be added here
  # server will be selected based on load
  # the value of id should be unique
  etherpad_hosts:
    -
      id: "node_01"
      host: "http://host.docker.internal:9001"
      api_key: "eb2fb3fb78ca29eb6896852517d34a1be5f320664e3cce3a522a06dfa278f169"
azure_cognitive_services_speech:
  enabled: false
  subscription_keys:
    -
      id: "key_1"
      # https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/get-started-text-to-speech?pivots=programming-language-go&tabs=linux%2Cterminal#prerequisites
      subscription_key: "your_key_here"
      service_region: westus2
      # Azure has limit to max concurrent connection for single key.
      # you should communicate with azure to know your limit. Default 20
      max_connection: 20
analytics_settings:
  enabled: true
  # if you've multiple plugNmeet servers then make sure that
  # all plugNmeet servers can access this directory
  # otherwise it may fail to fetch file. This path can be NSF or other network path
  files_store_path: ./analytics
  token_validity: 30m

```
My environment is Windows 10.
Sincerely, I hope you can give me some advice.
