### ISSUE TITLE
nats serve config has store_dir, which prevents the need decoupling.

### ISSUE THREAD

**Issue by gedw99** [mynaparrot/plugNmeet-server#563]
store_dir should be an env variable.

```yaml

jetstream: {
    store_dir: /data/jetstream
}
```

The config and the volume where you store data should be separated.

this will make deployment scaling out much easier
